services:
  mysql:
    image: mysql:8.0
    container_name: kuke-board-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.4
    container_name: kuke-board-redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:3.8.0
    container_name: kuke-board-kafka
    ports:
      - "9092:9092"

volumes:
  mysql-data: